### ISSUE TITLE
Simulating EEG 

### ISSUE THREAD

**Issue by stefanosIoannou** [bfinl/DeepSIF#1]
Dear authors,

Thanks for sharing the code. I am trying to reproduce the model's training set, i.e. generating the synthetic tvb data - I am quite new to this field. Do you generate the single source activity for each one of 998 regions by calling:
`python generate_tvb_data.py --a_start 0 --a_end 998`
using the connectivity_998.zip or just the 10 regions you mention in the README.md:
`python generate_tvb_data.py --a_start 0 --a_end 10` ?

Best,
Stef

**Comment by RuifengZheng** [comment]
It is "python generate_tvb_data.py --a_start 0 --a_end 998". And there are connectivity_76.zip and connnectivity_998.zip files. If the former is chosen, it is --a_end 76
